<a href="https://colab.research.google.com/github/shikhorroy/machine-learning/blob/main/01.%20numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Learning Numpy Array

In [18]:
import numpy as np

In [19]:
arr = np.array([1,2,3, 4, 5])

In [20]:
arr.shape

(5,)

In [21]:
arr[:] = 5
arr

array([5, 5, 5, 5, 5])

In [25]:
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [3, 2, 1,4, 4]])
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 3,  2,  1,  4,  4]])

In [26]:
arr2[1:, :2]

array([[6, 7],
       [3, 2]])

In [27]:
arr2[1]

array([ 6,  7,  8,  9, 10])